name: CI

on:
  push:
    branches:
        - main
    path-ignore:
        - README.md
  pull_request:
    branches:
        - main
    path-ignore:
        - README.md

env:
    DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer

jobs:
  test:
    runs-on: macos-latest

    steps:
        - uses: actions/checkout@v3

        - name: Install Mint
          run: brew install mint

        - name: Xcode build
          run: make build-debug

        - name: Xcode test
          run: make test


