name: CI

on:
    push:
    branches:
        - main
    path-ignore:
        - README.md
    pull_request:
    branches:
        - main
    path-ignore:
        - README.md

env:
    DEVELOPER_DIR: /Applications/Xcode_13.2.1.app

jobs:
    test:
        runs-on: macos-latest
        steps:
        - name: Select Xcode version # Xcode 12.4 を使う
        run: sudo xcode-select -s '/Applications/Xcode_13.2.1.app/Contents/Developer'
        - name: Show Xcode version
        run: xcodebuild -version
        - name: Build # シミュレーター向けにビルド
        run: xcodebuild -sdk iphonesimulator -configuration Debug build
